### ISSUE TITLE
Bones are created at the incorrect position

### ISSUE THREAD

**Issue by jralley** [Duduf-dev/Duik#23]
Hi, I'm running into an issue when I create bones using the puppet pin tool on layers imported from Illustrator. The bones and IK work fine, but the they are positioned down and to the right of where the layer is, just outside of my composition. I'm using AE CC on Mac OS X 10.9.5 and Duik v14.11.

**Comment by naeemsofi** [comment]
this problem is still in duduf 14.23
tell now what to do?
i am stuck from 2 days for this issue

**Comment by Nico-Duduf** [comment]
Found what goes wrong : the coordinates of puppet pins are not the same when checking the "continuously rasterize" option with AI Files.
I'll have to find how to create bones in this particular case,
For now, if you want to use bones with vectors, do not use this "continuously rasterize".
If you have definitions issues and need to create bones, you may precompose the vector layers, and resize those precomps to big sizes and use them as pixels without continuous rasterize (scaling the vectors inside the comp)

**Comment by Nico-Duduf** [comment]
Won't fix, as testing a puppet tool on vector layers with "continuously rasterize" enabled shows that those layers can't be scaled correctly anyway, so the option would be useless.

Anyway, a workaround is to convert the AI Layers in AFX Shape layers (the option can be found right clicking on the layer inside AFX).

**Comment by ColoradoW** [comment]
I ran into the exact issue in the latest version - this workaround of converting the AI layers to shape layers worked for me. Great plugin, and thanks for the work around as well.

**Comment by edgregor** [comment]
I have an issue with AE CC 2017. 
Imported photshop rasterized layers (for example, 2 seperate legs)
put pins on each separately.
add bones to first leg, fine.
add bones to second leg, bones are created in right spot but artwork of the layer snaps to location of first leg. 
This consistently happens.

**Comment by Nico-Duduf** [comment]
@edgregor you have to rename pins before creating bones

**Comment by edgregor** [comment]
Got it!
Thank you! Seems it would be good if AE incremented pins per project instead of per layer, that would help if you forget to rename pins for your awesome plugin. Thanks again!

**Comment by Understandingcat** [comment]
Hellos!
I seem to have the same problem when using the puppet tool, on the precomposed layers, in AE 2017 CC. The pins end up down and to the right from the layer. Attaching the before and after screnshots. Would appreciate the help with this one. Thanks!


<img width="1440" alt="screenshot 2017-02-11 13 08 26" src="https://cloud.githubusercontent.com/assets/25705469/22853661/dc9be116-f05c-11e6-894c-b503687cc945.png">
<img width="1440" alt="screenshot 2017-02-11 13 08 33" src="https://cloud.githubusercontent.com/assets/25705469/22853662/dc9c3b48-f05c-11e6-9ab2-bf6462006ff1.png">

**Comment by Nico-Duduf** [comment]
Hi,

Did you turn on the "continuously rasterize" option on the layer?
And can you try again renaming the pins before?

**Comment by Understandingcat** [comment]
No, from the start I didn't turn "continuously rasterize" on as the shapes I believe were created directly in Ae. Turning it on didn't help, though.

The pins turned up this way already for the first round, so I didn't have a chance to rename them.

**Comment by Nico-Duduf** [comment]
Can you send me the aep so I can have a look?
Can't find what's wrong with only the screenshots ;)

**Comment by juancarlosgzrz** [comment]
Was this bug fixed?

**Comment by Nico-Duduf** [comment]
Yes, it has been fixed in the latest update of Duik (15.2)
But there are still issues on puppet tools combined to shape layers. One should always precompose a shape layer before using the puppet tool with it.

Sometimes, in rare cases, there are bugs when there are several compositions with the same name in the project, try to avoid that too.

**Comment by juancarlosgzrz** [comment]
Nope, the bug is still there. I can't use Continuous rasterize which that's why I use vectors in the first place. Is this bug fixable?

**Comment by Nico-Duduf** [comment]
Well, no, this is not fixable: the puppet tool is a Pixel tool, incompatible with continuous rasterization, which is a vectors approach

**Comment by juancarlosgzrz** [comment]
What if you create your own vector based position puppet tool inside Duik? It would be a workaround.

**Comment by Nico-Duduf** [comment]
Easier said than done ;)

This would mean develop an entirely new plugin for After Effects, which is much more complicated than a script like Duik. And most of all, time-consuming.

A simpler workaround is to scale up the layers and precompose them.
Or working with a storyboard, and build the puppets at the size you need them, not relying on vectors to be able to scale them

**Comment by juancarlosgzrz** [comment]
Sure it is, it was just a question, even though I didn't know it would be so hard. Thank you for your effort.

**Comment by zanshevar** [comment]
Hi all. I have a solution to that problem. Make sure you have 1080 quality on your vector in AI, then export it to PSD (retain layers) then import it to AE, uncheck continuously rasterize. And thats it. The quality of the vector will remain good and not pixelated. 

Thanks
